{{- if .Values.dataexchange.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly.fullname" . }}-dx-config
  labels:
  {{- include "firefly.labels" . | nindent 4 }}
stringData:
  config.json: |
    {
      "api": {
        "hostname": "0.0.0.0",
        "port": 3000
      },
      "p2p": {
        "hostname": "0.0.0.0",
        "port": 3001,
        "endpoint": "https://{{ include "firefly.dataexchangeP2PHost" . }}"
      },
      "peers": {{ toJson .Values.dataexchange.peers }}
    }
{{- end }}
