{{- if .Values.dataexchange.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "firefly.fullname" . }}-dx
  labels:
    {{- include "firefly.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "firefly.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.dataexchange.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "firefly.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.dataexchange.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.dataexchange.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.dataexchange.securityContext | nindent 12 }}
          image: "{{ .Values.dataexchange.image.repository }}:{{ .Values.dataexchange.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dataexchange.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: p2p
              containerPort: 3001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.dataexchange.resources | nindent 12 }}
      {{- with .Values.dataexchange.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataexchange.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataexchange.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
