{{- if .Values.ipfs.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "firefly.fullname" . }}-ipfs
  labels:
    {{- include "firefly.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "firefly.fullname" . }}-ipfs
  selector:
    matchLabels:
      {{- include "firefly.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ipfs.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "firefly.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.ipfs.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.ipfs.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.ipfs.securityContext | nindent 12 }}
          image: "{{ .Values.ipfs.image.repository }}:{{ .Values.ipfs.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ipfs.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.ipfs.resources | nindent 12 }}
      {{- with .Values.ipfs.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ipfs.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ipfs.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
