{{- if .Values.ipfs.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "firefly.fullname" . }}-ipfs
  labels:
    {{- include "firefly.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "firefly.fullname" . }}-ipfs
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "firefly.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ipfs.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "firefly.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.ipfs.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.ipfs.podSecurityContext | nindent 8 }}
      containers:
        - name: ipfs
          securityContext:
            {{- toYaml .Values.ipfs.securityContext | nindent 12 }}
          image: "{{ .Values.ipfs.image.repository }}:{{ .Values.ipfs.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ipfs.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5001
              protocol: TCP
            - name: gateway
              containerPort: 8080
              protocol: TCP
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /webui*/}}
{{/*              port: http*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /webui*/}}
{{/*              port: http*/}}
          env:
            - name: LIBP2P_FORCE_PNET
              value: "1"

            # TODO what is this?
            - name: IPFS_SWARM_KEY
              value: |
                /key/swarm/psk/1.0.0/
                /base16/
                ebe17725f8082e32a622efdbfc60b75d3a7b9ea827f3d683afaac3d1649d40c0
          resources:
            {{- toYaml .Values.ipfs.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data/ipfs
              name: {{ include "firefly.fullname" . }}-ipfs-data
            - mountPath: /export
              name: {{ include "firefly.fullname" . }}-ipfs-staging
      {{- with .Values.ipfs.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ipfs.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ipfs.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "firefly.fullname" . }}-ipfs-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: {{ include "firefly.fullname" . }}-ipfs-staging
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  {{- end }}
