ganache:
  image:
    repository: "docker.io/trufflesuite/ganache-cli"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  imagePullSecrets: [ ]
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: { }

  podSecurityContext: { }
  # fsGroup: 2000

  securityContext: { }
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  service:
    type: ClusterIP
    port: 8545

  resources: { }
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: { }

  tolerations: [ ]

  affinity: { }

cert-manager:
  installCRDs: false

org1:
  nameOverride: org-1-firefly
  fullnameOverride: org-1-firefly

  postgresql:
    nameOverride: org-1-firefly-psql
    fullnameOverride: org-1-firefly-psql

  firefly:
    nameOverride: org-1-firefly
    fullnameOverride: org-1-firefly
    config:
      preInit: true
      adminEnabled: true
      debugEnabled: true
      organizationName: org-1
      organizationIdentity: 0xeb7284ce905e0665b7d42cabe31c76c45da1d331
      fireflyContractAddress: /instances/contract

      postgresUrl: postgres://postgres:s3r3n1ty2005@org-1-firefly-psql:5432?sslmode=disable
      ethconnectUrl: http://org-1-firefly-ethconnect
      ipfsApiUrl: http://org-1-firefly-ipfs:5001
      ipfsGatewayUrl: http://org-1-firefly-ipfs:8080

    dataexchange:
      certificate:
        enabled: true
        issuerRef:
          name: selfsigned-ca
          kind: ClusterIssuer

      tlsSecret:
        enabled: false
  ethconnect:
    gethUrl: "http://{{ .Release.Name }}-firefly-testnet-ganache:8545"
