
core:
  debugEnabled: true

dataexchange:
  certificate:
    enabled: true
    issuerRef:
      name: selfsigned-ca
      kind: ClusterIssuer

  tlsSecret:
    enabled: false

ethconnect:
  enabled: true
  gethUrl: http://doesnotexist:8545

