name: Helm

on:
  pull_request:
    branches:
      - main
    paths:
      - "deploy/charts/**/*"
jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup helm
        uses: azure/setup-helm@v1

      - name: setup chart-testing
        uses: helm/chart-testing-action@v2.0.1

#      - name: Run chart-testing (list-changed)
#        id: list-changed
#        run: |
#          changed=$(ct list-changed)
#          if [[ -n "$changed" ]]; then
#            echo "::set-output name=changed::true"
#          fi

      - name: setup kind
        uses: engineerd/setup-kind@v0.5.0

      - name: install cert-manager for testing
        run: |
          kubectl create ns cert-manager || true
          kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.4.0/cert-manager.crds.yaml
          helm repo add jetstack https://charts.jetstack.io || true
          helm install --skip-crds -n cert-manager cert-manager jetstack/cert-manager --wait
          kubectl apply -n cert-manager -f deploy/manifests/tls-issuers.yaml

      - name: lint charts
        run: ct lint --charts deploy/charts/firefly

      - name: test charts
        run: ct install --charts deploy/charts/firefly
