apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly.fullname" . }}-config
  labels:
  {{- include "firefly.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    {{- if .Values.core.debugEnabled }}
    log:
      level: debug
    debug:
      port: 6060
    {{- end }}
    http:
      port: 5000
      address: 0.0.0.0
    admin:
      port: 5001
      address: 0.0.0.0
      enabled: true
      preinit: true
    ui:
      path: ./frontend
    node:
      name: {{ .Values.config.organizationName }}-{{ include "firefly.fullname" . }}
    org:
      name: {{ .Values.config.organizationName }}
      identity: {{ .Values.config.organizationIdentity }}
    blockchain:
      {{ toYaml .Values.config.blockchain | nindent 6 }}
    database:
      type: postgres
      postgres:
        {{- if .Values.postgresql.enabled }}
        url: postgres://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPostgresPassword }}@{{ .Values.postgresql.fullnameOverride }}:5432?sslmode=disable
        {{- else }}
        url: {{ .Values.config.postgresUrl }}
        {{- end }}
        migrations:
          auto: true
    publicstorage:
      type: ipfs
      ipfs:
        {{- if .Values.ipfs.enabled }}
        api:
          url: http://{{ include "firefly.fullname" . }}-ipfs:5001
        gateway:
          url: http://{{ include "firefly.fullname" . }}-ipfs:8080
        {{- else }}
        api:
          url: {{ .Values.config.ipfsApiUrl }}
        gateway:
          url: {{ .Values.config.ipfsGatewayUrl }}
        {{- end }}
    dataexchange:
      {{- if .Values.dataexchange.enabled }}
      https:
        url: http://{{ include "firefly.fullname" . }}-dx:{{ .Values.dataexchange.service.apiPort }}
      {{- else }}
      https:
        url: {{ .Values.config.dataexchangeUrl }}
      {{- end }}
